### ISSUE TITLE
Doesn't work with 1.15

### ISSUE THREAD

**Issue by Craluminum2413** [DeviatorTX/BetterLogs#1]
```csharp
[Error] Exception thrown during handling event OnSaveGameLoaded: System.Exception: Requested asset [betterlogs:recipes/grid/betterlog.json] could not be found
   at Vintagestory.Common.FolderOrigin.LoadAsset(IAsset asset)
   at Vintagestory.Common.AssetManager.GetMany(String partialPath, String domain, Boolean loadAsset)
   at Vintagestory.Common.AssetManager.GetMany[T](ILogger logger, String fullPath, String domain)
   at Vintagestory.ServerMods.RecipeLoader.LoadGridRecipes()
   at Vintagestory.ServerMods.RecipeLoader.OnSaveGameLoaded()
   at Vintagestory.API.Common.Action.Invoke()
   at Vintagestory.Server.ServerEventManager.TriggerSaveGameLoaded()
```
```csharp
[Error] Couldn't spawn entity Vintagestory.API.Common.EntityPlayer with id 2 and code game:player - it's Type is null!
[Error] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Entities.Entity.GetBehavior[T]()
   at Vintagestory.Server.ServerMain.FinalizePlayerIdentification(_D8SGpER0sDpbfSCfmROokDx4zox packet, ConnectedClient client, String entitlements)
   at Vintagestory.Server.ServerMain.HandlePlayerIdentification(_ljf6OBTFbnANXFI64oSIpWHEFFc p, ConnectedClient client)
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket)
```

**Comment by DeviatorTX** [comment]
Should be working now. Let me know if you still get any errors with the new release. Thanks.
